version: "3"
name: "csie-camp-backbone"

services:
    server:
        build: .
        image: csie-camp-backbone
        restart: unless-stopped
        command: bash -c "npx prisma db push && npm run server"
        env_file:
            - .env
        expose:
            - "${PORT}:${PORT}"
        depends_on:
            - db
            - redis
    studio:
        build: .
        image: csie-camp-backbone
        restart: unless-stopped
        expose:
            - 5555:5555
        command: npx prisma studio
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env
        expose:
            - 5432:5432
        volumes:
            - db-data:/database
    redis:
        image: redis:latest
        restart: unless-stopped
        expose:
            - 6379:6379
        volumes:
            - redis:/redis
    tunnel:
        image: cloudflare/cloudflared:latest
        command: "tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}"
        restart: unless-stopped
        environment:
            TUNNEL_TRANSPORT_PROTOCOL: "http2"
        depends_on:
            - server
            - studio

volumes:
    db-data:
    redis:
