version: '3'
volumes:
  db-data:

services:
  server:
    build: .
    ports: 
      - "8080:8080"
    container_name: server
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: db
    env_file:
      - .env
    expose:
      - 8180:8080
    volumes:
      - db-data:/var/lib/postgresql/data
